---
# Use Ubuntu 'trusty' distribution
sudo: required
dist: xenial
services: docker

install:
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - chmod +x one_for_all.sh
  - docker-compose -f docker-compose.test.yml -p ci build
  - docker-compose -f docker-compose.test.yml -p ci up -d

script:
  - docker logs -f test

after_script:
  - docker-compose down
